name: release-please

on:
  push:
    branches:
      - main
      - "[0-9].[0-9].[0-9]"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Determine if branch is for a pre-release
        id: pre-branch
        run: |
          if [[ ${{ github.ref_name }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi
      - uses: google-github-actions/release-please-action@dependabot/npm_and_yarn/release-please-16.3.0
        with:
          release-type: ruby
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          prerelease-type: pre
          default-branch: "${{ github.ref_name }}"
          versioning-strategy: "${{ steps.pre-branch.outputs.match && 'prerelease' || 'default' }}"
          prerelease: ${{ steps.pre-branch.outputs.match }}
